// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_TitleHome;
lv_obj_t * ui_ChooseYourPlantLabel;
void ui_event_ButtonToP1(lv_event_t * e);
lv_obj_t * ui_ButtonToP1;
lv_obj_t * ui_Label6;
void ui_event_ButtonToP2(lv_event_t * e);
lv_obj_t * ui_ButtonToP2;
lv_obj_t * ui_Label7;
void ui_event_ButtonToP3(lv_event_t * e);
lv_obj_t * ui_ButtonToP3;
lv_obj_t * ui_Label8;


// SCREEN: ui_Plant_1
void ui_Plant_1_screen_init(void);
lv_obj_t * ui_Plant_1;
lv_obj_t * ui_TitleP1;
void ui_event_ChoosePlantP1(lv_event_t * e);
lv_obj_t * ui_ChoosePlantP1;
lv_obj_t * ui_CPLabel1;
lv_obj_t * ui_P1Display;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_HumLabel;
lv_obj_t * ui_SoilpH;
lv_obj_t * ui_pHLabel;
lv_obj_t * ui_SoilMoisture;
lv_obj_t * ui_MoisLabel;
lv_obj_t * ui_LightIntensity;
lv_obj_t * ui_LuxLabel;
lv_obj_t * ui_TempData;
lv_obj_t * ui_HumData;
lv_obj_t * ui_pHData;
lv_obj_t * ui_MoisData;
lv_obj_t * ui_LuxData;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;


// SCREEN: ui_Plant_2
void ui_Plant_2_screen_init(void);
lv_obj_t * ui_Plant_2;
lv_obj_t * ui_TitleP2;
void ui_event_ChoosePlantP2(lv_event_t * e);
lv_obj_t * ui_ChoosePlantP2;
lv_obj_t * ui_CPLabel2;
lv_obj_t * ui_P1Display1;
lv_obj_t * ui_Temperature1;
lv_obj_t * ui_TempLabel1;
lv_obj_t * ui_Humidity1;
lv_obj_t * ui_HumLabel1;
lv_obj_t * ui_SoilpH1;
lv_obj_t * ui_pHLabel1;
lv_obj_t * ui_SoilMoisture1;
lv_obj_t * ui_MoisLabel1;
lv_obj_t * ui_LightIntensity1;
lv_obj_t * ui_LuxLabel1;
lv_obj_t * ui_TempData1;
lv_obj_t * ui_HumData1;
lv_obj_t * ui_pHData1;
lv_obj_t * ui_MoisData1;
lv_obj_t * ui_LuxData1;


// SCREEN: ui_Plant_3
void ui_Plant_3_screen_init(void);
lv_obj_t * ui_Plant_3;
lv_obj_t * ui_TitleP3;
void ui_event_ChoosePlantP3(lv_event_t * e);
lv_obj_t * ui_ChoosePlantP3;
lv_obj_t * ui_CPLabel3;
lv_obj_t * ui_P1Display2;
lv_obj_t * ui_Temperature2;
lv_obj_t * ui_TempLabel2;
lv_obj_t * ui_Humidity2;
lv_obj_t * ui_HumLabel2;
lv_obj_t * ui_SoilpH2;
lv_obj_t * ui_pHLabel2;
lv_obj_t * ui_SoilMoisture2;
lv_obj_t * ui_MoisLabel2;
lv_obj_t * ui_LightIntensity2;
lv_obj_t * ui_LuxLabel2;
lv_obj_t * ui_TempData2;
lv_obj_t * ui_HumData2;
lv_obj_t * ui_pHData2;
lv_obj_t * ui_MoisData2;
lv_obj_t * ui_LuxData2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonToP1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Plant_1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Plant_1_screen_init);
    }
}
void ui_event_ButtonToP2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Plant_2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Plant_2_screen_init);
    }
}
void ui_event_ButtonToP3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Plant_3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Plant_3_screen_init);
    }
}
void ui_event_ChoosePlantP1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}
void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ToggleLED(e);
    }
}
void ui_event_ChoosePlantP2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}
void ui_event_ChoosePlantP3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Plant_1_screen_init();
    ui_Plant_2_screen_init();
    ui_Plant_3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
