// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleHome = lv_label_create(ui_Home);
    lv_obj_set_width(ui_TitleHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleHome, 0);
    lv_obj_set_y(ui_TitleHome, -222);
    lv_obj_set_align(ui_TitleHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleHome, "Welcome to Smart Terrarium Portal");

    ui_ChooseYourPlantLabel = lv_label_create(ui_Home);
    lv_obj_set_width(ui_ChooseYourPlantLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChooseYourPlantLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChooseYourPlantLabel, 0);
    lv_obj_set_y(ui_ChooseYourPlantLabel, -150);
    lv_obj_set_align(ui_ChooseYourPlantLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChooseYourPlantLabel, "Please choose the plant you wish to monitor");

    ui_ButtonToP1 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_ButtonToP1, 100);
    lv_obj_set_height(ui_ButtonToP1, 50);
    lv_obj_set_x(ui_ButtonToP1, 0);
    lv_obj_set_y(ui_ButtonToP1, -80);
    lv_obj_set_align(ui_ButtonToP1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToP1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonToP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToP1, lv_color_hex(0x38D740), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// -71
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -80);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Plant 1");

    ui_ButtonToP2 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_ButtonToP2, 100);
    lv_obj_set_height(ui_ButtonToP2, 50);
    lv_obj_set_align(ui_ButtonToP2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToP2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonToP2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToP2, lv_color_hex(0x489AE8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Plant 2");

    ui_ButtonToP3 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_ButtonToP3, 100);
    lv_obj_set_height(ui_ButtonToP3, 50);
    lv_obj_set_x(ui_ButtonToP3, 0);
    lv_obj_set_y(ui_ButtonToP3, 80);
    lv_obj_set_align(ui_ButtonToP3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToP3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonToP3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToP3, lv_color_hex(0xF0E240), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 80);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Plant 3");

    lv_obj_add_event_cb(ui_ButtonToP1, ui_event_ButtonToP1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonToP2, ui_event_ButtonToP2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonToP3, ui_event_ButtonToP3, LV_EVENT_ALL, NULL);

}
