// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Plant_2_screen_init(void)
{
    ui_Plant_2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Plant_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleP2 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_TitleP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleP2, 0);
    lv_obj_set_y(ui_TitleP2, -222);
    lv_obj_set_align(ui_TitleP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleP2, "Welcome to Smart Terrarium Portal");

    ui_ChoosePlantP2 = lv_btn_create(ui_Plant_2);
    lv_obj_set_width(ui_ChoosePlantP2, 108);
    lv_obj_set_height(ui_ChoosePlantP2, 50);
    lv_obj_set_x(ui_ChoosePlantP2, 144);
    lv_obj_set_y(ui_ChoosePlantP2, -145);
    lv_obj_set_align(ui_ChoosePlantP2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChoosePlantP2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ChoosePlantP2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChoosePlantP2, lv_color_hex(0x489AE8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChoosePlantP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPLabel2 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_CPLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CPLabel2, 144);
    lv_obj_set_y(ui_CPLabel2, -145);
    lv_obj_set_align(ui_CPLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CPLabel2, "Choose Plant");

    ui_P1Display1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_P1Display1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_P1Display1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_P1Display1, -110);
    lv_obj_set_y(ui_P1Display1, -147);
    lv_obj_set_align(ui_P1Display1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_P1Display1, "Currently Displaying:\n\nPlant 2");

    ui_Temperature1 = lv_obj_create(ui_Plant_2);
    lv_obj_set_width(ui_Temperature1, 169);
    lv_obj_set_height(ui_Temperature1, 50);
    lv_obj_set_x(ui_Temperature1, 130);
    lv_obj_set_y(ui_Temperature1, -83);
    lv_obj_set_align(ui_Temperature1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temperature1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_TempLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel1, 130);
    lv_obj_set_y(ui_TempLabel1, -93);
    lv_obj_set_align(ui_TempLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel1, "Soil Temperature (°C)");
    lv_obj_set_style_text_align(ui_TempLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity1 = lv_obj_create(ui_Plant_2);
    lv_obj_set_width(ui_Humidity1, 169);
    lv_obj_set_height(ui_Humidity1, 50);
    lv_obj_set_x(ui_Humidity1, 130);
    lv_obj_set_y(ui_Humidity1, -23);
    lv_obj_set_align(ui_Humidity1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Humidity1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumLabel1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_HumLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel1, 130);
    lv_obj_set_y(ui_HumLabel1, -33);
    lv_obj_set_align(ui_HumLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel1, "Humidity (%)");
    lv_obj_set_style_text_align(ui_HumLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilpH1 = lv_obj_create(ui_Plant_2);
    lv_obj_set_width(ui_SoilpH1, 169);
    lv_obj_set_height(ui_SoilpH1, 50);
    lv_obj_set_x(ui_SoilpH1, 130);
    lv_obj_set_y(ui_SoilpH1, 37);
    lv_obj_set_align(ui_SoilpH1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoilpH1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pHLabel1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_pHLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pHLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pHLabel1, 130);
    lv_obj_set_y(ui_pHLabel1, 27);
    lv_obj_set_align(ui_pHLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pHLabel1, "Soil pH Value");
    lv_obj_set_style_text_align(ui_pHLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilMoisture1 = lv_obj_create(ui_Plant_2);
    lv_obj_set_width(ui_SoilMoisture1, 169);
    lv_obj_set_height(ui_SoilMoisture1, 50);
    lv_obj_set_x(ui_SoilMoisture1, 130);
    lv_obj_set_y(ui_SoilMoisture1, 97);
    lv_obj_set_align(ui_SoilMoisture1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoilMoisture1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MoisLabel1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_MoisLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoisLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoisLabel1, 130);
    lv_obj_set_y(ui_MoisLabel1, 87);
    lv_obj_set_align(ui_MoisLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoisLabel1, "Soil Moisture (%)");
    lv_obj_set_style_text_align(ui_MoisLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightIntensity1 = lv_obj_create(ui_Plant_2);
    lv_obj_set_width(ui_LightIntensity1, 169);
    lv_obj_set_height(ui_LightIntensity1, 50);
    lv_obj_set_x(ui_LightIntensity1, 130);
    lv_obj_set_y(ui_LightIntensity1, 157);
    lv_obj_set_align(ui_LightIntensity1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightIntensity1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LuxLabel1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_LuxLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxLabel1, 130);
    lv_obj_set_y(ui_LuxLabel1, 147);
    lv_obj_set_align(ui_LuxLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxLabel1, "Light Intensity (Lux)");
    lv_obj_set_style_text_align(ui_LuxLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempData1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_TempData1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempData1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempData1, 130);
    lv_obj_set_y(ui_TempData1, -73);
    lv_obj_set_align(ui_TempData1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempData1, "26.00");

    ui_HumData1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_HumData1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumData1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumData1, 130);
    lv_obj_set_y(ui_HumData1, -13);
    lv_obj_set_align(ui_HumData1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumData1, "50");

    ui_pHData1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_pHData1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pHData1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pHData1, 130);
    lv_obj_set_y(ui_pHData1, 47);
    lv_obj_set_align(ui_pHData1, LV_ALIGN_CENTER);

    ui_MoisData1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_MoisData1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoisData1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoisData1, 130);
    lv_obj_set_y(ui_MoisData1, 107);
    lv_obj_set_align(ui_MoisData1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoisData1, "50");

    ui_LuxData1 = lv_label_create(ui_Plant_2);
    lv_obj_set_width(ui_LuxData1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxData1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxData1, 130);
    lv_obj_set_y(ui_LuxData1, 167);
    lv_obj_set_align(ui_LuxData1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxData1, "1000");

    lv_obj_add_event_cb(ui_ChoosePlantP2, ui_event_ChoosePlantP2, LV_EVENT_ALL, NULL);

}
