// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Plant_3_screen_init(void)
{
    ui_Plant_3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Plant_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleP3 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_TitleP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleP3, 0);
    lv_obj_set_y(ui_TitleP3, -222);
    lv_obj_set_align(ui_TitleP3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleP3, "Welcome to Smart Terrarium Portal");

    ui_ChoosePlantP3 = lv_btn_create(ui_Plant_3);
    lv_obj_set_width(ui_ChoosePlantP3, 108);
    lv_obj_set_height(ui_ChoosePlantP3, 50);
    lv_obj_set_x(ui_ChoosePlantP3, 144);
    lv_obj_set_y(ui_ChoosePlantP3, -145);
    lv_obj_set_align(ui_ChoosePlantP3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChoosePlantP3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ChoosePlantP3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChoosePlantP3, lv_color_hex(0xF0E240), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChoosePlantP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPLabel3 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_CPLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CPLabel3, 144);
    lv_obj_set_y(ui_CPLabel3, -145);
    lv_obj_set_align(ui_CPLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CPLabel3, "Choose Plant");

    ui_P1Display2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_P1Display2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_P1Display2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_P1Display2, -110);
    lv_obj_set_y(ui_P1Display2, -147);
    lv_obj_set_align(ui_P1Display2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_P1Display2, "Currently Displaying:\n\nPlant 3");

    ui_Temperature2 = lv_obj_create(ui_Plant_3);
    lv_obj_set_width(ui_Temperature2, 169);
    lv_obj_set_height(ui_Temperature2, 50);
    lv_obj_set_x(ui_Temperature2, 130);
    lv_obj_set_y(ui_Temperature2, -83);
    lv_obj_set_align(ui_Temperature2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temperature2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_TempLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel2, 130);
    lv_obj_set_y(ui_TempLabel2, -93);
    lv_obj_set_align(ui_TempLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel2, "Soil Temperature (°C)");
    lv_obj_set_style_text_align(ui_TempLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity2 = lv_obj_create(ui_Plant_3);
    lv_obj_set_width(ui_Humidity2, 169);
    lv_obj_set_height(ui_Humidity2, 50);
    lv_obj_set_x(ui_Humidity2, 130);
    lv_obj_set_y(ui_Humidity2, -23);
    lv_obj_set_align(ui_Humidity2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Humidity2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumLabel2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_HumLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel2, 130);
    lv_obj_set_y(ui_HumLabel2, -33);
    lv_obj_set_align(ui_HumLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel2, "Humidity (%)");
    lv_obj_set_style_text_align(ui_HumLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilpH2 = lv_obj_create(ui_Plant_3);
    lv_obj_set_width(ui_SoilpH2, 169);
    lv_obj_set_height(ui_SoilpH2, 50);
    lv_obj_set_x(ui_SoilpH2, 130);
    lv_obj_set_y(ui_SoilpH2, 37);
    lv_obj_set_align(ui_SoilpH2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoilpH2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pHLabel2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_pHLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pHLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pHLabel2, 130);
    lv_obj_set_y(ui_pHLabel2, 27);
    lv_obj_set_align(ui_pHLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pHLabel2, "Soil pH Value");
    lv_obj_set_style_text_align(ui_pHLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilMoisture2 = lv_obj_create(ui_Plant_3);
    lv_obj_set_width(ui_SoilMoisture2, 169);
    lv_obj_set_height(ui_SoilMoisture2, 50);
    lv_obj_set_x(ui_SoilMoisture2, 130);
    lv_obj_set_y(ui_SoilMoisture2, 97);
    lv_obj_set_align(ui_SoilMoisture2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoilMoisture2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MoisLabel2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_MoisLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoisLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoisLabel2, 130);
    lv_obj_set_y(ui_MoisLabel2, 87);
    lv_obj_set_align(ui_MoisLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoisLabel2, "Soil Moisture (%)");
    lv_obj_set_style_text_align(ui_MoisLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightIntensity2 = lv_obj_create(ui_Plant_3);
    lv_obj_set_width(ui_LightIntensity2, 169);
    lv_obj_set_height(ui_LightIntensity2, 50);
    lv_obj_set_x(ui_LightIntensity2, 130);
    lv_obj_set_y(ui_LightIntensity2, 157);
    lv_obj_set_align(ui_LightIntensity2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightIntensity2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LuxLabel2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_LuxLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxLabel2, 130);
    lv_obj_set_y(ui_LuxLabel2, 147);
    lv_obj_set_align(ui_LuxLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxLabel2, "Light Intensity (Lux)");
    lv_obj_set_style_text_align(ui_LuxLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempData2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_TempData2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempData2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempData2, 130);
    lv_obj_set_y(ui_TempData2, -73);
    lv_obj_set_align(ui_TempData2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempData2, "26.00");

    ui_HumData2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_HumData2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumData2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumData2, 130);
    lv_obj_set_y(ui_HumData2, -13);
    lv_obj_set_align(ui_HumData2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumData2, "50");

    ui_pHData2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_pHData2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pHData2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pHData2, 130);
    lv_obj_set_y(ui_pHData2, 47);
    lv_obj_set_align(ui_pHData2, LV_ALIGN_CENTER);

    ui_MoisData2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_MoisData2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoisData2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoisData2, 130);
    lv_obj_set_y(ui_MoisData2, 107);
    lv_obj_set_align(ui_MoisData2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoisData2, "50");

    ui_LuxData2 = lv_label_create(ui_Plant_3);
    lv_obj_set_width(ui_LuxData2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxData2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxData2, 130);
    lv_obj_set_y(ui_LuxData2, 167);
    lv_obj_set_align(ui_LuxData2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxData2, "1000");

    lv_obj_add_event_cb(ui_ChoosePlantP3, ui_event_ChoosePlantP3, LV_EVENT_ALL, NULL);

}
